name: Build on pull request to master

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "NODE_OPTIONS=--max-old-space-size=8192" >> $GITHUB_ENV
      - run: |
          echo NODE_OPTIONS: ${NODE_OPTIONS}
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Call linter
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - name: Build code
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
